// Generated .IDL file (by Roberto Olivares 1/5/2000)
// 
// Typelib filename: IMA2.tlb

[
  uuid(44683FF0-73C0-11D3-BFB7-00E02903BD46),
  version(2.5),
  helpstring("(IMA2 Base) - Base Interfaces")
]
library IMA2
{
    // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
    importlib("StdOle2.tlb");

// *****************************************************************************************************************************
// Interface Prototypes
// *****************************************************************************************************************************
	interface IComponent;
	interface IContainer;
//	interface IContainerChildren;
    interface IBindings;
    interface IConfigureBindings;
	interface ILocator;

// *****************************************************************************************************************************
// Interface Prototypes
// *****************************************************************************************************************************
	interface ILocatorAdvanced;
	interface ILocatorEventProvider;
	interface ILocatorEvents;
	interface IDistributingInfoProvider;
	interface IManager;

// *****************************************************************************************************************************
// Enumerations
// *****************************************************************************************************************************
	typedef [uuid(4845E655-EBE3-42a1-A1A2-03B9694DC278), version(2.5), hidden]
    enum IMA2_ContainerAction {
        CE_Add = 0,
        CE_Remove = 1,
        CE_Locate = 2,
    } IMA2_ContainerAction;

	typedef [uuid(C5E023BB-969A-4B67-8D33-561A9C2E1D6A), version(2.5), hidden]
    enum IMA2_BindingType {
        BT_Default = 0,
        BT_Temporary = 1,
        BT_Optional = 2,
        BT_Cached = 4,
        BT_Collection = 255
    } IMA2_BindingType;

	typedef [uuid(7F2F28CB-6178-4d44-B1E0-722092EAA1AE), version(2.5)]
    enum IMA2_LocatorAction {
        LE_Locate = 0,
        LE_Register = 1,
        LE_UnRegister = 2,
        LE_Subscribe = 3,
        LE_Unsubscribe = 4,
        LE_Connect = 5,
		LE_Disconnect = 6,
		LE_ActivateSeq = 7,
		LE_DeactivateSeq = 8
    } IMA2_LocatorAction;

// *****************************************************************************************************************************
// Structures
// *****************************************************************************************************************************
    typedef [uuid(A50E6DEF-D9DA-440F-8CD3-C3123DE4979A), version(2.5)]
    struct IMA2_BindingInfo {
        BSTR Name;
        BSTR Path;
		SAFEARRAY(BSTR) PIDs;
        SAFEARRAY(BSTR) IIDs;
        IMA2_BindingType BindType;
    } IMA2_BindingInfo;

    typedef [uuid(CE57220D-E969-452c-8E86-29FB0AC7BB51), version(2.5)]
    struct IMA2_DistributingInfo {
        BSTR Name;
        BSTR Path;
        BSTR PID;
        BSTR Machine;
		long Process;
		long Thread;
		VARIANT_BOOL IsContainer;
    } IMA2_DistributingInfo;

// *****************************************************************************************************************************
// Interfaces
// *****************************************************************************************************************************
    [
      odl, uuid(44683FF9-73C0-11D3-BFB7-00E02903BD46), version(2.5), nonextensible, oleautomation,
	  helpstring("Implemented by all IMA2 compliant objects.")
    ]
    interface IComponent : IUnknown {
        [id(0)]					HRESULT Construct			([in] BSTR Path, [in] BSTR PID, [in] ILocator** pAL);
        [id(1)]					HRESULT Destruct			();
        [id(2)]					HRESULT Load				([in] VARIANT Data);
        [id(3)]					HRESULT Save				([out, retval] VARIANT* pData);
        [id(4)]					HRESULT DataSize			([out, retval] long* pSize);
        [id(5), propget]		HRESULT Distributing		([out, retval] IMA2_DistributingInfo* pInfo);
        [id(6), propget]		HRESULT Bindings			([out, retval] IBindings ** pBindings);
    };

    [
      odl, uuid(44683FF7-73C0-11D3-BFB7-00E02903BD46), version(2.5), nonextensible, oleautomation, hidden,
	  helpstring("Implemented by IMA2 objects wishing to contain other components.")
    ]
    interface IContainer : IUnknown {
        [id(0)]					HRESULT CreateComponent		([in] BSTR PID, [in] BSTR Machine, [out, retval] IComponent**);
        [id(1), propget]		HRESULT InnateComponents	([out, retval] SAFEARRAY(BSTR)*);
    };

	[
      odl, uuid(690214B3-1A69-4A53-9B22-FB6CD110BA43), version(1.0), nonextensible, oleautomation,
	  helpstring("Implemented by all IMA2 binding collections, interface to user.")
    ]
    interface IBindings : IUnknown {
        [id(0), propget]		HRESULT Pointers			([in] BSTR Name, [out, retval] IComponent** rhs);
        [id(1), propget]		HRESULT Collections			([in] BSTR Name, [out, retval] SAFEARRAY(IComponent*)*);
        [id(2), propget]		HRESULT Settings			([out, retval] IConfigureBindings** rhs);
    };

    [
      odl, uuid(179E6B2E-AE75-4fa4-81EF-DD6F7AC09BA4), version(1.0), nonextensible, oleautomation, hidden,
	  helpstring("Implemented by all IMA2 binding collections, interface to shell.")
    ]
    interface IConfigureBindings : IUnknown {
        [id(0)]					HRESULT Construct			([in] BSTR Owner, [in] ILocator** AL);
        [id(1)]					HRESULT Destruct			();
		[id(2)]					HRESULT Add					([in] IMA2_BindingInfo* BindInfo);
        [id(3)]					HRESULT Remove				([in] BSTR Name);
        [id(4), propget]		HRESULT Item				([in] BSTR Name, [out, retval] IMA2_BindingInfo*);
        [id(5), propget]		HRESULT Items				([out, retval] SAFEARRAY(IMA2_BindingInfo)*);
        [id(6), propget]		HRESULT Count				([out, retval] long* rhs);
    };

	[
      odl, uuid(44683FF5-73C0-11D3-BFB7-00E02903BD46), version(2.5), nonextensible, oleautomation,
	  helpstring("Implemented by the IMA2 Locating service to provide hierarchy and remoting support.")
    ]
    interface ILocator : IUnknown {
        [id(0)]					HRESULT Locate				([in] BSTR Path, [out, retval] IComponent **);
        [id(1), propget]		HRESULT Machine				([out, retval] BSTR*);
    };

// *****************************************************************************************************************************
// Interfaces
// *****************************************************************************************************************************
	[
      odl, uuid(14DA3CEF-CCCA-4c01-9C5A-ACD5C9B11233), version(2.5), nonextensible, oleautomation, 
	  helpstring("Implemented by the IMA2 Locating service to provide advanced hierarchy and remoting support.")
    ]
    interface ILocatorAdvanced : IUnknown {
        [id(0), propget]		HRESULT Components			([out, retval] SAFEARRAY(BSTR)*);
        [id(1), propget]		HRESULT Locators			([out, retval] SAFEARRAY(BSTR)*);
        [id(2)]					HRESULT Register			([in] IComponent * Cmp);
		[id(3)]					HRESULT Unregister			([in] BSTR Path);
        [id(4)]					HRESULT Connect				([in] BSTR Machine);
        [id(5)]					HRESULT Disconnect			([in] BSTR Machine);
        [id(6)]					HRESULT BatchOperation		([in] IMA2_LocatorAction * Action, [in] SAFEARRAY(VARIANT)* Args, [out, retval] SAFEARRAY(VARIANT)*);
    };

    [
      odl, uuid(44683FFC-73C0-11D3-BFB7-00E02903BD46), version(2.5), nonextensible, oleautomation,
	  helpstring("Implemented by objects wishing to recieve IMA2 Locator events.")
    ]
    interface ILocatorEvents : IUnknown {
        [id(0)]					HRESULT OnRegistrationEvent	([in] IMA2_LocatorAction* Action, [in] SAFEARRAY(IMA2_DistributingInfo)* DIs);
        [id(1)]					HRESULT OnOtherEvent		([in] IMA2_LocatorAction* Action, [in] SAFEARRAY(BSTR)* Args);
    };	

    [
      odl, uuid(72ADA84B-6E1F-4fd1-A8E8-B58374985EB1), version(2.5), nonextensible, oleautomation,
	  helpstring("Implemented by the IMA2 Locator / Event Service to provide registration events.")
    ]
    interface ILocatorEventProvider : IUnknown {
        [id(0)]					HRESULT Subscribe			([in] ILocatorEvents * Sink, [in] BSTR Key, [in] IMA2_LocatorAction * Flags);
        [id(1)]					HRESULT Unsubscribe			([in] BSTR Key);
        [id(2), propget]		HRESULT Clients				([out, retval] SAFEARRAY(BSTR)*);
    };

	[
      odl, uuid(62299D66-3375-48c5-9568-698F3ADEF96D), version(2.5), nonextensible, oleautomation,
	  helpstring("Implemented by a service that provides IMA2 object hierarchy type information.")
    ]
    interface IDistributingInfoProvider : IUnknown {
		[id(0), propget]		HRESULT Item				([in] BSTR Path, [out, retval] IMA2_DistributingInfo *);
		[id(1), propget]		HRESULT Items				([out, retval] SAFEARRAY(IMA2_DistributingInfo) *);
        [id(2), propget]		HRESULT Count				([out, retval] long *);
		[id(3)]					HRESULT Search				([in] BSTR Criteria, [out, retval] SAFEARRAY(IMA2_DistributingInfo) *);
        [id(4), propget]		HRESULT Components			([out, retval] SAFEARRAY(BSTR)*);
        [id(5), propget]		HRESULT Locators			([out, retval] SAFEARRAY(BSTR)*);
    };

	interface IManager;
	[
		odl, uuid(8F783C23-E023-11D3-8DF1-0020AFF12FBD), version(2.5), nonextensible, oleautomation,
		helpstring("Implemented by objects wishing to be a component manager.")
	]
	interface IManager : IUnknown {
		[id(0), propget]    	HRESULT Component			([out, retval] IComponent** Cmp);
		[id(0), propput]    	HRESULT Component			([in] IComponent* Cmp);
		[id(1)]    				HRESULT Update				();
	};
};
